% Comparison of data provided by ADS and data generated by the orbit 
% propagation algorithm.
% ADS data are located in the Excel and txt files.
% 3 set of data have been generated by the orbit propagation algorithm:
% HPOP_ADS.mat: generation every minute (similar to ADS data)
% HPOP_ADS2.mat: generation every 10sec
% HPOP_ADS_FineMan: HPOP_ADS2.mat + a maneuver